n1 = int(input('digite um número da sorte:'))
print(n1)
ex2 = float(input('digite mais um número:'))
print(ex2)
print('é um número flutuante,{}'.format(ex2))
cor = bool(input('qual cor tem minha blusa?'))
print(cor)
nome = str(input('qual seu nome?'))
print('oi,{}'.format(nome))
